networks:
  delivery-net:
    driver: bridge

services:
  # =========================================
  # TIER 1: INFRASTRUCTURE
  # =========================================
  postgres:
    image: postgres:18.3
    container_name: dev_postgres
    restart: unless-stopped
    networks:
      - delivery-net
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "keycloak_db,customer_db"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d keycloak_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6.3-alpine
    container_name: dev_redis
    restart: unless-stopped
    networks:
      - delivery-net
    command: >
      redis-server
        --requirepass ${REDIS_PASSWORD}
        --maxmemory   256mb
        --maxmemory-policy allkeys-lru
        --appendonly  yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================================
  # TIER 2: IDENTITY & ACCESS MANAGEMENT
  # =========================================
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    restart: unless-stopped
    networks:
      - delivery-net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY_HEADERS: xforwarded
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - "/opt/keycloak/bin/kc.sh start --optimized || echo 'Optimized start failed! Falling back to standard start...' && /opt/keycloak/bin/kc.sh start"

  keycloak-waiter:
    image: curlimages/curl:8.20.0
    networks:
      - delivery-net
    depends_on:
      keycloak:
        condition: service_started
    restart: "no"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - 'i=0; echo "Waiting for Keycloak..."; while ! curl -s -f http://keycloak:9000/keycloak/health/ready > /dev/null; do i=$$((i+1)); if [ $$i -ge 20 ]; then echo "ERROR: Keycloak timeout after 200 seconds"; exit 1; fi; echo "Attempt $$i/20 - retrying in 10s..."; sleep 10; done; echo "Keycloak is ready."'

  # =========================================
  # TIER 3: APPLICATION SERVICES
  # =========================================
  customer-service:
    build:
      context: ../../
      dockerfile: src/Services/Cargo.CustomerService/Dockerfile
    container_name: customer-service
    restart: unless-stopped
    networks:
      - delivery-net
    depends_on:
      postgres:
        condition: service_healthy
      keycloak-waiter:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: ${CS_ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__CustomerDb: ${CS_Connection_String}
      Gateway__BaseUrl: ${CS_GW_Url}
      Keycloak__Authority: ${CS_KC_Authority}
      Keycloak__MetadataAddress: ${CS_KC_MetadataAddress}
      Keycloak__Audience: ${CS_KC_Audience}
      Keycloak_Backend__ClientId: ${CS_KC_Backend_ClientId}
      Keycloak_Backend__ClientSecret: ${CS_KC_Backend_ClientSecret}
      Keycloak_Backend__BaseUrl: ${CS_KC_BaseUrl}
      Keycloak_Backend__Realm: ${CS_KC_Realm}
      Storage__Endpoint: ${CS_CF_Storage_Endpoint}
      Storage__AccessKey: ${CS_CF_Storage_AccessKey}
      Storage__SecretKey: ${CS_CF_Storage_SecretKey}
      Storage__BucketName: ${CS_CF_Storage_BucketName}
      Storage__ForcePathStyle: ${CS_CF_Storage_ForcePathStyle}
      EmailSettings__SmtpHost: ${SMTP_HOST}
      EmailSettings__SmtpPort: ${SMTP_PORT}
      EmailSettings__From: ${SMTP_FROM}
      EmailSettings__Password: ${SMTP_PASSWORD}
      REDIS__ConnectionString: ${REDIS_CONNECTION_STRING}

  # =========================================
  # TIER 4: API GATEWAY (YARP)
  # =========================================
  gateway:
    build:
      context: ../../
      dockerfile: src/Gateway/Cargo.Gateway/Dockerfile
    container_name: cargo_gateway
    restart: unless-stopped
    networks:
      - delivery-net
    depends_on:
      keycloak-waiter:
        condition: service_completed_successfully
      customer-service:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: ${GW_ASPNETCORE_ENVIRONMENT}
      Keycloak__Authority: ${CS_KC_Authority}
      Keycloak__MetadataAddress: ${CS_KC_MetadataAddress}
      Keycloak__Audience: ${CS_KC_Audience}
      ReverseProxy__Clusters__customer-cluster__Destinations__customer-service__Address: ${GW_Customer_Service_Address}

volumes:
  postgres_data:
  redis_data:
